Drop database if exists employee;
Create Database Employee;
use Employee;
 -- project table  
Create Table proj_table (
PROJECT_ID varchar(10) Primary key,
PROJECT_NAME VARCHAR(100),
DOMAIN VARCHAR(100),
`START _DATE` VARCHAR(20), -- BACKTICKS FOR READING THE COLUMN NAME CORRECTLY AS IT HAS A SPAE 
CLOSURE_DATE VARCHAR(20),
DEV_QTR VARCHAR(10),
STATUS VARCHAR(30)
);
-- EMPLOYEE RECORD TABLE 
CREATE TABLE emp_record_table (
EMP_ID VARCHAR(10) PRIMARY KEY,
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(100),
GENDER VARCHAR(10),
ROLE VARCHAR(100),
DEPT VARCHAR(50),
EXP INT,
COUNTRY VARCHAR(100),
CONTINENT VARCHAR(20),
SALARY INT,
EMP_RATING INT,
MANAGER_ID VARCHAR(10),
PROJ_ID VARCHAR(10),
CONSTRAINT Tj_emp_proj foreign key (PROJ_ID) REFERENCES proj_table(PROJECT_ID)
);
-- DATA SCIENCE TEAM TABLE
CREATE TABLE data_science_team (
EMP_ID VARCHAR(10),
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(100),
GENDER VARCHAR(10),
ROLE VARCHAR(100),
DEPT VARCHAR(50),
EXP INT,
COUNTRY VARCHAR(100),
CONTINENT VARCHAR (100),
PRIMARY KEY(EMP_ID)
);
-- 3. EMPLOYEE DEPARTMENT MAPPING
select e. EMP_ID,
e.FIRST_NAME,
e.LAST_NAME,
e.GENDER,
e.DEPT as DEPARTMENT
FROM emp_record_table e;
-- 4A. EMPLOYEEE RATING LESS THAN 2 
select e. EMP_ID,e.FIRST_NAME,e.LAST_NAME,e.GENDER,e.DEPT as DEPARTMENT,EMP_RATING 
FROM emp_record_table e
WHERE EMP_RATING<2;
-- 4B. EMPLOYEE RATNG GREATER THAN 4
select e. EMP_ID,e.FIRST_NAME,e.LAST_NAME,e.GENDER,e.DEPT as DEPARTMENT,EMP_RATING 
FROM emp_record_table e
WHERE EMP_RATING>4;
-- 4C.EMPLOYEE RATING BETWEEN 2 AND 4
select e. EMP_ID,e.FIRST_NAME,e.LAST_NAME,e.GENDER,e.DEPT as DEPARTMENT,EMP_RATING 
FROM emp_record_table e
WHERE EMP_RATING BETWEEN 2 AND 4;
-- 5.EMPLOYEES FROM FINNACE DEPARTMENT 
select concat(e.FIRST_NAME, ' ' ,e.LAST_NAME)as NAME
FROM emp_record_table e
where e.DEPT='FINANCE';
-- 6. MANAGER-EMPLOYEE REPORTING SCHEMA
SELECT m.emp_id,
concat(m.FIRST_NAME,' ',M.LAST_NAME) AS MANAGER_NAME,
COUNT(e.EMP_ID) as reporter_count
FROM emp_record_table m
join emp_record_table as e
on e.MANAGER_ID=m.EMP_ID
GROUP BY m.EMP_ID, m.FIRST_NAME, m.LAST_NAME
order by REPORTER_COUNT desc;
-- 7.UNION OF HEALTH AND FINANCE EMPLOYEES
SELECT * FROM emp_record_table WHERE DEPT='HEALTHCARE'
UNION 
SELECT * FROM emp_record_table WHERE DEPT='FINANCE'
-- 8. EMPLOYEE AND MAX RATING DETAILS
SELECT EMP_ID, FIRST_NAME,LAST_NAME, ROLE, DEPT AS DEPARTMENT,EMP_RATING,
MAX(EMP_RATING) OVER (PARTITION BY DEPT) AS MAX_RATING_OF_DEPARTMENT
FROM emp_record_table
order by DEPT,EMP_RATING DESC;
-- ALTERNATE VERSION
SELECT EMP_ID,FIRST_NAME,LAST_NAME,ROLE, DEPT AS DEPARTMENT,EMP_RATING,
(SELECT MAX(E2.EMP_RATING)
FROM emp_record_table e2
where e2.dept=e1.dept) as Max_rating_of_department
from emp_record_table e1
order by dept,emp_rating desc;
-- 9. MINIMUM AND MAXIMUM SALARY BY ROLE
SELECT ROLE,
MIN(SALARY) AS MIN_SALARY,
MAX(SALARY) AS MAX_SALARY
FROM emp_record_table
GROUP BY ROLE;

-- 10. EMPLOYEE RANKS BY EXPERIENCE
SELECT EMP_ID, FIRST_NAME, LAST_NAME, EXP,
DENSE_RANK() OVER(ORDER BY EXP DESC) AS EXP_RANK
FROM emp_record_table;

-- 11. EMPLOYEES SALARY GREATER THAN 6000
SELECT EMP_ID, FIRST_NAME, LAST_NAME, COUNTRY, CONTINENT, SALARY
FROM emp_record_table
WHERE SALARY>6000;

-- 12. EMPLOYEES WITH EXPERIENCE GREATER THAN 10
SELECT * FROM emp_record_table
WHERE EMP_ID IN (
SELECT EMP_ID 
FROM emp_record_table
WHERE EXP>10
);
-- 13. STORED PROCEDURE FOR RETREVING EMPLOYEES WITH EXP>3
DELIMITER $$
CREATE PROCEDURE SP_EXP_GT_3()
BEGIN 
SELECT * FROM emp_record_table
WHERE EXP>3;
END $$
DELIMITER ;
CALL SP_EXP_GT_3();
-- 14. ASSIGNING ROLES TO DATA SCIENTISTA BASED ON STORED PROCEDURE.
DELIMITER $$
DROP FUNCTION IF EXISTS fn_std_role $$

CREATE FUCNTION fn_std_role(exp_int INT)
returns varchar(50)
deterministic 
begin 
if exp_years<=2 then
return 'JUNIOR DATA SCIENTIST';
elseif exp_years>2 and exp_years<=5 then
return 'ASSOCIATE DATA SCIENTIST';
elseif exp_years>5 and exp_years<=10 then
return 'SENIOR DATA SCIENTIST';
elseif exp_years>10 and exp_years<=12 then
return 'LEAD DATA SCIENTIST';
elseif exp_years>12 and exp_years<=16 then
return 'MANAGER';
else 
return 'OUT OF STANDARAD';
end if;
end $$
delimiter ;
select EMP_ID,FIRST_NAME, LAST_NAME, EXP,
ROLE AS CURRENT_ROLE,
fn_std_role(EXP) AS STANDARD_ROLE,
CASE WHEN UPPER(ROLE)=fn_std_role(EXP) THEN 'MATCH' ELSE 'MISMATCH' END AS ROLE_CHECK
FROM data_science_team;
-- 15. Index for first name
CREATE INDEX IDX_FRST_NAME
ON emp_record_table(FIRST_NAME);
EXPLAIN SELECT * FROM emp_record_table
WHERE FIRST_NAME='ERIC'
-- 16. BONUS BASED ON RATING
SELECT EMP_ID,FIRST_NAME,LAST_NAME, SALARY, EMP_RATING,
(0.05*SALARY*EMP_RATING) AS BONUS
FROM emp_record_table;
-- 17. AVERAGE SALARY BY COUNTRY AND CONTINENT
SELECT CONTINENT, COUNTRY, AVG(SALARY) AS AVG_SALARY
FROM emp_record_table
GROUP BY CONTINENT,COUNTRY
ORDER BY CONTINENT, COUNTRY;












